import { getStylesHook } from 'hooks/useStyles';
import globalStyles, { Colors } from 'styles';

export default getStylesHook({
  container: {
    flex: 1,
    width: '100%',
  },
  cardContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: -20,
    paddingBottom: 24,
  },
  executeFormButton: {
    marginHorizontal: 16,
    marginTop: 30,
  },
  modalHeader: {
    height: 56,
    borderBottomColor: Colors.BORDER,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
  },
  modalHeaderText: {
    marginRight: 16,
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    lineHeight: 24,
    color: Colors.BlueNewColor,
  },
  closeBtn: {
    height: 24,
    width: 24,
  },
  noteWrap: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 9,
    backgroundColor: Colors.WHITE,
  },
  note: {
    fontStyle: 'italic',
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontSize: 12,
    lineHeight: 16,
    color: Colors.LIGHTTextDisable,
    marginBottom: 3,
  },
  leaderBoardJoinContainer: {
    ...globalStyles.centered,
    backgroundColor: Colors.BlueNewColor,
    width: 343,
    height: 40,
    borderRadius: 10,
    marginBottom: 12,
  },
  realLeaderBoardJoinContainer: {
    ...globalStyles.centered,
    backgroundColor: Colors.Yellow5,
    width: 343,
    height: 40,
    borderRadius: 10,
    marginBottom: 12,
  },
  leaderBoardJoinText: {
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.WHITE,
    fontSize: 16,
  },
  wrapSwitch: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  leaderBoardChangeAccountText: {
    fontWeight: 'bold',
    textTransform: 'uppercase',
    color: Colors.BlueNewColor,
    textAlign: 'center',
    fontSize: 11,
    paddingBottom: 8,
  },
  leaderBoardChangeAccountEdit: {
    fontWeight: 'bold',
    textDecorationColor: Colors.BlueNewColor,
    textDecorationLine: 'underline',
    textDecorationStyle: 'solid',
    textTransform: 'uppercase',
    color: Colors.BlueNewColor,
    textAlign: 'center',
    fontSize: 11,
    paddingBottom: 8,
  },
  textBold: {
    fontWeight: 'bold',
    fontSize: 12,
    color: Colors.LIGHTTextDisable,
    fontFamily: 'Roboto',
    fontStyle: 'italic',
    lineHeight: 16,
  },
});
