import { lightColors as Colors } from 'styles';
import { getStylesHook } from 'hooks/useStyles';

export default getStylesHook({
  modalBackground2: {
    flex: 1,
    backgroundColor: Colors.BACKGROUND_MODAL,
    paddingHorizontal: 16,
  },
  modalTitle2: {
    height: 52,
    borderBottomWidth: 1,
    borderBottomColor: Colors.BORDER,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalContentContainer2: {
    backgroundColor: Colors.WHITE,
    alignItems: 'stretch',
    borderRadius: 21,
    width: '100%',
    paddingBottom: 16,
  },
  modalTitleText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.BlueNewColor,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
  },
  executeModalEachItem: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 44,
    borderBottomColor: Colors.BORDER,
    borderBottomWidth: 1,
    paddingHorizontal: 16,
  },
  executeModalEachItem2: {
    height: 44,
    paddingHorizontal: 16,
  },
  executeLabelText: {
    flex: 1,
    fontWeight: 'bold',
    color: Colors.LIGHTTextBigTitle,
    textAlign: 'left',
    fontSize: 14,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
  },
  executeLabelValue: {
    flex: 1,
    fontSize: 14,
    fontWeight: 'bold',
    color: Colors.LIGHTTextContent,
    textAlign: 'right',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
  },
  executeLabelValue2: {
    flex: 1,
    fontSize: 14,
    color: Colors.LIGHTTextContent,
    textAlign: 'right',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  executeLabelValue3: {
    fontSize: 14,
    color: Colors.LIGHTTextContent,
    textAlign: 'right',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: 'bold',
  },
  executeBuyValue: {
    fontSize: 14,
    color: Colors.DARK_GREEN,
    textAlign: 'right',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  executeSellValue: {
    fontSize: 14,
    color: Colors.LIGHTRed,
    textAlign: 'right',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  paddingHorizontal16: {
    paddingHorizontal: 16,
  },
  marginBottom: {
    marginBottom: 10,
  },
  marginTop17: {
    marginTop: 17,
  },
  executeFormButton2: {
    backgroundColor: Colors.BlueNewColor,
    height: 44,
    borderRadius: 10,
    width: '100%',
    marginTop: 17,
    marginBottom: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  executeFormButtonText2: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Colors.WHITE,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
  },
  cancelExecuteFormButton2: {
    backgroundColor: Colors.LIGHTBackground,
    height: 44,
    borderRadius: 10,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelExecuteFormButtonText2: {
    fontSize: 16,
    color: Colors.LIGHTTextContent,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  scrollView: {
    flexGrow: 1,
    justifyContent: 'center',
  },
});
