import { Platform } from 'react-native';
import globalStyles, { lightColors as Colors } from 'styles';
import { getStylesHook } from 'hooks/useStyles';

export default getStylesHook({
  colorUp: {
    color: Colors.DARK_GREEN,
  },
  containerPeriod: {
    marginTop: 8,
  },
  container: {
    backgroundColor: Colors.WHITE,
  },
  screenOptionContainer: {
    height: 54,
    paddingHorizontal: 16,
    justifyContent: 'flex-end',
  },
  rankNumberText: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.LIGHTTextTitle,
  },
  screenOption: {
    height: 44,
    backgroundColor: Colors.LIGHTBGTab,
    borderRadius: 10,
    paddingHorizontal: 3,
    paddingVertical: 3,
  },
  optionContainerSelected: {
    backgroundColor: Colors.WHITE,
  },
  optionContainer: {
    borderRadius: 10,
  },
  selectedText: {
    fontSize: 14,
    fontWeight: '700',
    color: Colors.BlueNewColor,
  },
  unselectedText: {
    fontSize: 14,
    color: Colors.LIGHTTextTitle,
  },
  investingReturnListEachItem: {
    flexDirection: 'row',
    height: 60,
    backgroundColor: Colors.WHITE,
    marginHorizontal: 8,
    borderBottomColor: Colors.BORDER,
    borderBottomWidth: 1,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 2.65,
    elevation: 4,
  },
  investingReturnFirstItem: {
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  topInfo: {
    height: 36,
    alignItems: 'center',
    backgroundColor: 'red',
  },
  rankContainer: {
    height: 24,
    width: 24,
    borderRadius: 15,
    backgroundColor: Colors.LIGHTBackground,
    marginTop: 0,
  },
  rankContainer2: {
    paddingLeft: 18,
    paddingVertical: 11,
  },
  nameContainer: {
    paddingLeft: 5,
    marginVertical: 8,
  },
  rankingStatusText: {
    fontSize: 10,
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    width: 20,
    textAlign: 'center',
  },
  bottomInfoItemLeft: {
    paddingRight: 16,
  },
  bottomInfoItemRight: {
    backgroundColor: Colors.LIGHTTitleTable,
    borderRadius: 8,
    paddingHorizontal: 8,
    height: 36,
    width: 120,
    marginLeft: 'auto',
  },
  bottomInfoLeaderboard: {
    backgroundColor: Colors.LIGHTTitleTable,
    borderRadius: 8,
    marginRight: 8,
    marginVertical: 8,
    paddingHorizontal: 8,
    width: 80,
    marginLeft: 'auto',
  },
  bottomInfoLeaderboard1: {
    backgroundColor: '#062769',
    borderRadius: 8,
    marginRight: 8,
    marginVertical: 8,
    paddingHorizontal: 8,
    width: 84,
    height: 44,
    marginLeft: 'auto',
  },
  followerContainer: {
    backgroundColor: Colors.LIGHTTitleTable,
    borderRadius: 8,
    paddingLeft: 8,
    paddingRight: 11,
  },
  followerText: {
    fontSize: 12,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: 'bold',
    color: Colors.LIGHTTextTitle,
    marginLeft: 'auto',
  },
  followerText1: {
    fontSize: 12,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: 'bold',
    color: Colors.WHITE,
    marginLeft: 'auto',
  },
  followerTextNumberContainer: {
    alignItems: 'flex-end',
  },
  followerTextNumberContainer2: {
    justifyContent: 'flex-end',
  },
  followerTextNumber: {
    fontSize: 14,
    color: Colors.LIGHTTextContent,
  },
  returnRateText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '500',
    fontFamily: Platform.OS === 'ios' ? 'DINOT' : 'DINOT-Light',
    fontStyle: 'normal',
    textAlign: 'right',
  },
  chartContainer: {
    width: 140,
  },
  avatarContainer: {
    width: 36,
    height: '100%',
    marginRight: 8,
  },
  nameText: {
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.LIGHTTextBigTitle,
    fontSize: 14,
    paddingRight: 10,
    marginBottom: 3,
  },
  nameText1: {
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.WHITE,
    fontSize: 14,
    paddingRight: 10,
    marginBottom: 3,
  },
  mainBlue: {
    color: Colors.MainBlue,
  },
  usernameText: {
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.MainBlue,
    fontSize: 11,
    paddingRight: 10,
  },
  usernameText1: {
    fontWeight: 'bold',
    fontSize: 11,
    color: '#15FDE1',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    lineHeight: 16,
  },
  note: {
    marginLeft: 16,
    marginBottom: 8,
    fontStyle: 'normal',
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontSize: 12,
    lineHeight: 16,
    color: Colors.LIGHTTextDisable,
  },
  underlay: {
    width: '100%',
    height: '100%',
    backgroundColor: Colors.BlueNewColor,
    position: 'absolute',
    zIndex: -1,
  },
  backgroundNoContest: {
    zIndex: 1,
    width: 300,
    height: 300,
  },
  backgroundNoContest1: {
    zIndex: 1,
    width: 250,
    marginVertical: Platform.OS === 'ios' ? 30 : 10,
    marginTop: 50,
  },
  backgroundNoContest2: {
    zIndex: 1,
    width: 321,
  },
  backgroundNoContest3: {
    zIndex: 1,
    width: '100%',
    height: 366,
    marginTop: Platform.OS === 'ios' ? 0 : -70,
    marginLeft: -50,
  },
  botUserContainer: {
    backgroundColor: Colors.LIGHTTitleTable,
  },
  botUserReturnContainer: {
    backgroundColor: Colors.LIGHTBackground,
  },
  avatarImg: {
    ...globalStyles.centered,
    marginLeft: 15,
    marginVertical: 10,
    height: 40,
    width: 40,
    borderRadius: 40,
    position: 'relative',
  },
  avatarImgText: {
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.WHITE,
    fontSize: 17,
  },
  skeletonHeight: {
    height: 60,
  },
  textWhite: {
    color: Colors.WHITE,
  },
  leaderBoardOfMeContainer: {
    ...globalStyles.centered,
    position: 'absolute',
    bottom: 0,
    backgroundColor: '#3255BC',
    width: 359,
    height: 60,
    marginBottom: Platform.OS === 'ios' ? 14 : 4,
    marginHorizontal: 8,
    borderRadius: 15,
    zIndex: 2,
  },
  marginBottomContainer: {
    marginBottom: Platform.OS === 'ios' ? 80 : 60,
  },
  marginTop2: {
    marginTop: 2,
  },
  marginTopRanking: {
    marginTop: Platform.OS === 'ios' ? -2 : -8,
  },
  modalBackground: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'flex-end',
    flexDirection: 'row',
  },
  leaderBoardJoinText: {
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.WHITE,
    fontSize: 16,
  },
  preJoinContestText2: {
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: '#FFD745',
    fontSize: 16,
    lineHeight: 22,
  },
  paddingBtn: {
    paddingHorizontal: 16,
    paddingVertical: 30,
  },
  preJoinContestText: {
    color: '#B9FFFF',
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 16,
    lineHeight: 22,
    paddingBottom: 16,
  },
  preJoinContestText3: {
    color: '#B9FFFF',
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 18,
  },
  preJoinContestText4: {
    color: Colors.WHITE,
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 18,
  },
  marginHorizontal16: {
    marginHorizontal: 16,
  },
  paddingHorizontal16: {
    paddingHorizontal: 16,
  },
  paddingHorizontal50: {
    paddingHorizontal: 50,
  },
  BGWhite: {
    backgroundColor: Colors.WHITE,
  },
  marginText: {
    marginTop: 40,
  },
  paddingTop30: {
    paddingTop: 30,
  },
  noDataContestText: {
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.LIGHTYellow,
    fontSize: 16,
    lineHeight: 18,
    textAlign: 'center',
    paddingVertical: 12,
  },
  noDataContestText1: {
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.BLACK,
    fontSize: 14,
    lineHeight: 18,
    textAlign: 'center',
  },
  containFlatList: {
    ...globalStyles.container,
    paddingBottom: 100,
  },
  paddingVertical12: {
    paddingVertical: 12,
  },
  pb100: {
    paddingBottom: 100,
  },
  mt50: {
    marginTop: -50,
  },
  loadingIcon: {
    justifyContent: 'flex-start',
    paddingBottom: 20,
  },
  leaderBoardJoinContent2: {
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.BLACK,
    fontSize: 14,
    lineHeight: 22,
  },
  bgContainer: {
    width: '100%',
    height: '100%',
    flex: 1,
    overflow: 'hidden',
    position: 'absolute',
    zIndex: -1,
  },
  leaderboardContainer: {
    ...globalStyles.container,
    ...globalStyles.containerBackground,
  },
  imgBg: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    zIndex: -1,
  },
  listEmptyContainer: {
    ...globalStyles.container2,
    ...globalStyles.alignCenter,
    backgroundColor: Colors.WHITE,
    paddingTop: 30,
    paddingHorizontal: 16,
    paddingBottom: 100,
  },
  listFooterStyle: {
    width: '100%',
    height: '100%',
    backgroundColor: Colors.WHITE,
  },
});
