import globalStyles, { isPlatformIOs, lightColors as Colors, textStyles } from 'styles';
import { getStylesHook } from 'hooks/useStyles';

export default getStylesHook({
  container: {
    flex: 1,
    backgroundColor: Colors.WHITE,
  },
  containerBackground: {
    backgroundColor: Colors.WHITE,
    // flex: 1,
  },
  titleContainer: {
    ...globalStyles.flexDirectionRow,
    ...globalStyles.justifySpaceBetween,
    ...globalStyles.alignCenter,
    backgroundColor: Colors.WHITE,
    marginHorizontal: 16,
  },
  titleContainer1: {
    backgroundColor: Colors.WHITE,
    marginHorizontal: 16,
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
  },
  titleHeader: {
    backgroundColor: Colors.WHITE,
    marginTop: 8,
  },
  headerTitleInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 18,
  },
  titleCashTransactionContainer: {
    backgroundColor: Colors.WHITE,
    borderBottomColor: Colors.BORDER,
    borderBottomWidth: 1,
    borderRadius: 5,
  },
  titleCashTransaction: {
    paddingHorizontal: 7,
    paddingVertical: 1,
    fontWeight: '700',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 12,
    lineHeight: 16,
    color: Colors.BlueNewColor,
  },
  TitleType: {
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 14,
    color: Colors.BlueNewColor,
    marginVertical: 23,
  },
  TitleStatus: {
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 14,
    color: Colors.BlueNewColor,
    marginVertical: 23,
  },
  Title: {
    fontWeight: '700',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 14,
    color: Colors.BlueNewColor,
    marginVertical: 22,
  },
  TitleBank: {
    fontWeight: '700',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 14,
    color: Colors.BlueNewColor,
    marginVertical: 22,
  },
  TextType: {
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 14,
    color: Colors.LIGHTTextContent,
    marginLeft: 10,
    width: 235,
  },
  TextBeneficiary: {
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 14,
    color: Colors.LIGHTTextContent,
  },
  TitleTransferFee: {
    fontWeight: '700',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 14,
    color: Colors.BlueNewColor,
    marginVertical: 23,
  },
  screenOption: {
    marginTop: 10,
    marginBottom: 8,
    width: 343,
    marginHorizontal: 16,
    height: 44,
    backgroundColor: Colors.LIGHTBGTab,
    borderRadius: 10,
    paddingHorizontal: 3,
    paddingVertical: 3,
    flexDirection: 'row',
  },
  optionContainer: {
    borderRadius: 10,
  },
  optionContainerSelected: {
    backgroundColor: Colors.WHITE,
  },
  selectedText: {
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 14,
    fontWeight: '700',
    color: Colors.BlueNewColor,
  },
  unselectedText: {
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 14,
    color: Colors.LIGHTTextTitle,
  },
  rowDataText: {
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 14,
    color: Colors.LIGHTTextBigTitle,
  },
  rowDataNumber: {
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 14,
    color: Colors.LIGHTTextContent,
    alignItems: 'flex-end',
  },
  rowData: {
    paddingHorizontal: 16,
    paddingVertical: 5,
    borderBottomColor: Colors.BORDER,
    borderBottomWidth: 1,
    justifyContent: 'space-between',
  },
  textInputContainerStyle: {
    backgroundColor: Colors.LIGHTTitleTable,
    height: 44,
    width: 158,
    marginLeft: 5,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.LIGHTBackground,
  },
  textInputCityContainerStyle: {
    backgroundColor: Colors.LIGHTTitleTable,
    height: 44,
    width: 163.5,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.LIGHTBackground,
  },
  textInputContentContainerStyle: {
    backgroundColor: Colors.LIGHTTitleTable,
    height: 81,
    width: 343,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.LIGHTBackground,
    marginTop: -10,
  },
  textInputStyle: {
    height: '100%',
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.BLACK,
    marginLeft: 10,
  },
  textInputTransferAmount: {
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 14,
    height: '100%',
  },
  iconStyle: {
    marginLeft: 2,
  },
  TitleOut: {
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 14,
    color: Colors.BLACK,
  },
  TitleAmount: {
    textAlign: 'right',
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 14,
    color: Colors.BLACK,
    width: 170,
  },
  executeFormContainer: {
    marginBottom: 10,
    marginTop: 20,
    paddingBottom: 10,
    backgroundColor: Colors.WHITE,
    marginHorizontal: 16,
    alignItems: 'center',
  },
  executeFormButton: {
    backgroundColor: Colors.BlueNewColor,
    height: 44,
    width: 343,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  executeFormButtonText: {
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.WHITE,
  },
  marginBottomHaveBorder16: {
    borderTopWidth: 1,
    borderColor: Colors.LIGHTBackground,
    marginBottom: 16,
  },
  marginBottom16: {
    marginBottom: 16,
  },
  marginLeft16: {
    marginLeft: 16,
  },
  marginRight16: {
    marginRight: 16,
  },
  border1: {
    borderRightColor: Colors.BORDER,
    borderRightWidth: 1,
  },
  cellStyle: {
    borderRightColor: Colors.BORDER,
    borderRightWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
  },
  noNumber: {
    color: Colors.LIGHTTextContent,
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
  },
  date: {
    color: Colors.LIGHTTextContent,
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
  },
  paddingRight: {
    paddingRight: 6,
  },
  opacityBackground: {
    backgroundColor: Colors.BACKGROUND_MODAL2,
  },
  editMarginBottom: {
    // marginBottom: (5),
  },
  rowDataValue: {
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 14,
    color: Colors.LIGHTTextContent,
    alignItems: 'flex-end',
  },
  modalBackground: {
    backgroundColor: Colors.BACKGROUND_MODAL2,
    alignItems: 'flex-end',
  },
  modalContentContainer: {
    backgroundColor: Colors.WHITE,
    borderTopLeftRadius: 21,
    borderTopRightRadius: 21,
    width: '100%',
    paddingBottom: 30,
    justifyContent: 'center',
  },
  modalContentContainer2: {
    backgroundColor: Colors.WHITE,
    width: '100%',
    borderRadius: 16,
    padding: 16,
  },
  modalTitle: {
    height: 52,
    borderBottomWidth: 1,
    borderBottomColor: Colors.BORDER,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  filterText: {
    fontWeight: '700',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 16,
    color: Colors.BlueNewColor,
    marginLeft: 16,
  },
  wholeContainerStyle: {
    width: 343,
    height: 44,
    marginTop: 9,
    marginBottom: 8,
    backgroundColor: Colors.LIGHTTitleTable,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.LIGHTBackground,
  },
  iconSearch: {
    marginLeft: 51,
  },
  rowDataTextBranch: {
    fontWeight: '700',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 14,
    color: Colors.LIGHTTextBigTitle,
    width: 343,
  },
  rowDataTextBank: {
    paddingVertical: 10,
    justifyContent: 'space-between',
    width: 235,
  },
  rowDataTextAccountType: {
    paddingVertical: 10,
    justifyContent: 'space-between',
    width: 325,
  },
  rowDataBank: {
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 14,
    color: Colors.LIGHTTextDisable,
    alignItems: 'flex-end',
  },
  listBankContainer: {
    height: 500,
  },
  listTypeContainer: {
    height: 100,
  },
  listStatusContainer: {
    height: 230,
  },
  TextBank: {
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 14,
    color: Colors.LIGHTTextContent,
    marginLeft: 10,
  },
  labelIconStyle: {
    width: 24,
    height: 24,
    color: Colors.LIGHTTextDisable,
  },
  CustomPicker: {
    // marginLeft: (38),
    justifyContent: 'flex-end',
  },
  CustomPickerStatus: {
    marginLeft: 28,
  },
  CustomPickerMall: {
    marginLeft: 5,
  },
  CustomPickerCity: {
    marginLeft: 16,
  },
  tooltipContent: {
    color: Colors.WHITE,
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 14,
    lineHeight: 18,
  },
  tooltip: {
    backgroundColor: Colors.BlueNewColor,
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderRadius: 13,
  },
  tooltipContainer: {
    marginTop: 6,
  },
  SeparatorContainer: {
    width: '100%',
    backgroundColor: Colors.LIGHTTitleTable,
  },
  textBlockStyle: {
    borderTopWidth: 1,
    borderColor: Colors.LIGHTBackground,
    paddingVertical: 14,
    ...globalStyles.flexDirectionRow,
    ...globalStyles.justifySpaceBetween,
    ...globalStyles.alignCenter,
  },
  optionTitle: {
    fontSize: 14,
    fontWeight: '700',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.LIGHTTextBigTitle,
  },
  optionContent: {
    fontSize: 14,
    fontWeight: '700',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.LIGHTTextBigTitle,
  },
  optionValue: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.LIGHTTextContent,
    width: 150,
    textAlign: 'right',
  },
  optionValueContent: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.LIGHTTextContent,
    width: 150,
    textAlign: 'right',
  },
  internalTransferContentBlock: {
    // marginHorizontal: (16),
  },
  textInputContainerContentStyle: {
    borderWidth: 1,
    borderRadius: 10,
    borderColor: Colors.BORDER,
    backgroundColor: Colors.LIGHTTitleTable,
    paddingHorizontal: 8,
  },
  textInputtransferAmountStyle: {
    height: '100%',
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 14,
    color: Colors.BLACK,
    marginLeft: 10,
  },
  typeTextInputContainerStyle: {
    width: 250,
    height: 44,
    backgroundColor: Colors.LIGHTTitleTable,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.LIGHTBackground,
    alignItems: 'center',
    flexDirection: 'row',
    marginHorizontal: 0,
    paddingHorizontal: 0,
    paddingRight: 8,
  },
  BeneficiaryTextInputContainerStyle: {
    width: 158,
    height: 44,
    backgroundColor: Colors.LIGHTTitleTable,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.LIGHTBackground,
    alignItems: 'center',
    flexDirection: 'row',
  },
  successfulContainer: {
    width: 345,
    height: 56,
    backgroundColor: Colors.DARKButtonGreen,
    borderRadius: 8,
    marginHorizontal: 16,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  SuccessTitle: {
    marginVertical: 18,
    marginLeft: 18,
  },
  ErrorContainer: {
    width: 345,
    height: 56,
    backgroundColor: Colors.LIGHTButtonRed,
    borderRadius: 8,
    marginHorizontal: 16,
  },
  textSuccessful: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.WHITE,
  },
  pickerModalStyle: {
    paddingHorizontal: 16,
  },

  tabBlock: {
    marginTop: 8,
  },
  customTab: {
    marginTop: 10,
  },
  tabViewStyles: {
    height: '100%',
  },
  executeFormDisableButton: {
    opacity: 0.5,
  },
  textInputContainerContentError: {
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: Colors.LIGHTTitleTable,
    paddingHorizontal: 8,
    borderColor: Colors.LIGHTRed,
  },
  wholeContainerContentStyleError: {
    width: 160,
    height: 44,
    marginBottom: 15,
  },
  wholeContainerContentStyle: {
    width: 160,
    height: 44,
  },
  SuccessContainer: {
    marginTop: 95,
  },

  //STATUS
  colorLightTextContent: {
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.LIGHTTextContent,
    fontSize: 14,
    marginLeft: 10,
    flex: 1,
    textAlign: 'left',
  },
  topInfo: {
    height: 14,
  },
  filterItemContainer: {
    paddingHorizontal: 16,
    height: 54,
    borderBottomWidth: 1,
    borderBottomColor: Colors.BORDER,
    alignItems: 'center',
    flexDirection: 'row',
  },
  filterTextValue: {
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 16,
  },
  filterTextValueType: {
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 16,
  },
  filterTextValueSelected: {
    color: Colors.MainBlue,
  },
  filterTextValueUnselected: {
    color: Colors.LIGHTTextTitle,
  },
  closeType: {
    marginRight: 16,
  },

  // new style for modal otp kis
  modalBackground1: {
    backgroundColor: Colors.BACKGROUND_MODAL2,
    justifyContent: 'flex-end',
    flex: 1,
  },
  modalBackground2: {
    flex: 1,
    backgroundColor: Colors.BACKGROUND_MODAL2,
    alignItems: 'center',
  },
  modalBackground3: {
    flex: 1,
    backgroundColor: Colors.BACKGROUND_MODAL2,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  modalScrollContentContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: Colors.WHITE,
    borderRadius: 21,
    width: 343,
    paddingHorizontal: 16,
    overflow: 'hidden',
  },
  modalTitleContainer: {
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalTitleText2: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    lineHeight: 24,
    textAlign: 'center',
    color: Colors.BlueNewColor,
  },
  spaceOtp: {
    marginTop: 17,
    marginBottom: 10,
    width: '100%',
  },
  executeFormButton3: {
    backgroundColor: Colors.BlueNewColor,
    width: '100%',
    height: 44,
    borderRadius: 10,
  },
  executeFormButton2: {
    backgroundColor: Colors.LIGHTBackground,
    width: '100%',
    height: 44,
    borderRadius: 10,
  },
  cancelExecuteFormButton2: {
    backgroundColor: Colors.LIGHTBackground,
    height: 44,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelExecuteFormButtonText2: {
    fontSize: 16,
    color: Colors.LIGHTTextContent,
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
  },
  executeFormButtonText2: {
    fontSize: 16,
    fontWeight: '700',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.WHITE,
  },
  executeFormButtonTextDisable: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.LIGHTTextDisable,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
  },
  scrollView: {
    flex: 1,
    justifyContent: 'center',
  },
  transferTime: {
    paddingTop: 10,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  heightHistoryTableNoData: {
    height: 224,
  },

  heightHistoryTable: {
    // bank transfer
    height: 440,
    paddingBottom: isPlatformIOs ? 30 : 50,
  },

  loadingText: {
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    textAlign: 'center',
    color: Colors.LIGHTTextDisable,
  },
  noDataCon: {
    width: 375,
    height: 162,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noDataText: {
    fontFamily: 'Roboto',
    marginTop: 16,
    fontSize: 16,
    color: Colors.LIGHTTextContent,
    textAlign: 'center',
  },
  posRelative: {
    position: 'relative',
  },
  wholeContainerContentStyle2: {
    width: '100%',
    height: 80,
    marginTop: 8,
  },
  contentStyle2: {
    flexDirection: 'column',
    marginHorizontal: 16,
  },
  dateSpace: {
    marginBottom: 16,
    flexDirection: 'row',
    width: '100%',
  },
  dateHorizontal: {
    marginHorizontal: 16,
    flex: 1,
  },
  dateSpace1: {
    marginRight: 16,
    flex: 1,
  },
  centerIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowTable: {
    alignItems: 'flex-end',
    flex: 1,
  },
  rowTable1: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
  },
  rowTable2: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'flex-end',
    borderRightColor: Colors.BORDER,
    borderRightWidth: 1,
    paddingRight: 6,
  },
  paaveLogoContainer: {
    paddingVertical: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  transactionErrorText: {
    ...textStyles.fontSize14,
    ...textStyles.roboto400,
    color: Colors.BLACK,
    paddingTop: 8,
    paddingBottom: 24,
    textAlign: 'center',
  },
  btnErrorContainer: {
    flex: 1,
    marginHorizontal: 8,
  },
  btnErrorText: {
    ...textStyles.fontSize13,
  },
});
