import { getStylesHook } from 'hooks/useStyles';
import { Platform } from 'react-native';
import globalStyles, { Colors } from 'styles';

export default getStylesHook({
  rankNumberText: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.LIGHTTextTitle,
  },
  rankContainer: {
    height: 24,
    width: 24,
    borderRadius: 15,
    backgroundColor: Colors.LIGHTBackground,
    marginTop: Platform.OS === 'android' ? 10 : 0,
  },
  rankContainer2: {
    paddingLeft: 18,
    paddingVertical: 11,
  },
  nameContainer: {
    paddingLeft: 5,
    marginVertical: 8,
  },
  rankingStatusText: {
    fontSize: 10,
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    marginLeft: 2,
  },
  bottomInfoLeaderboard: {
    backgroundColor: Colors.LIGHTBackground,
    borderRadius: 8,
    marginRight: 8,
    marginVertical: 8,
    paddingHorizontal: 8,
    width: 84,
    height: 44,
    marginLeft: 'auto',
  },
  followerText1: {
    fontSize: 12,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: 'bold',
    color: Colors.BLACK,
    marginLeft: 'auto',
  },
  returnRateText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '500',
    fontFamily: Platform.OS === 'ios' ? 'DINOT' : 'DINOT-Light',
    fontStyle: 'normal',
    textAlign: 'right',
  },
  nameText1: {
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.BLACK,
    fontSize: 14,
    paddingRight: 10,
    marginBottom: 3,
  },
  usernameText1: {
    fontWeight: 'bold',
    fontSize: 11,
    color: Colors.BlueNewColor,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    lineHeight: 16,
  },
  avatarImg: {
    ...globalStyles.centered,
    marginLeft: 15,
    marginVertical: 10,
    height: 40,
    width: 40,
    borderRadius: 40,
    position: 'relative',
  },
  avatarImgText: {
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.WHITE,
    fontSize: 17,
  },
  textBlack: {
    color: Colors.BLACK,
  },
  leaderBoardOfMeContainer: {
    ...globalStyles.centered,
    position: 'absolute',
    bottom: 0,
    backgroundColor: Colors.WHITE,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.5,
    shadowRadius: 20.0,
    elevation: 99,
    width: 359,
    height: 60,
    marginBottom: Platform.OS === 'ios' ? 20 : 4,
    marginHorizontal: 8,
    borderRadius: 15,
    zIndex: 9,
  },
  marginBottomContainer: {
    marginBottom: Platform.OS === 'ios' ? 80 : 60,
  },
  marginTop2: {
    marginTop: 2,
  },
  marginTopRanking: {
    marginTop: Platform.OS === 'ios' ? -2 : -8,
  },
  notRankedText: {
    fontWeight: 'bold',
    fontSize: 12,
    color: Colors.BlueNewColor,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    lineHeight: 16,
    textAlign: 'right',
  },
  mr10: {
    marginRight: 10,
  },
  spaceButton: {
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  // tooltip
  tooltipContainer: {
    marginTop: -4,
    marginLeft: Platform.OS === 'ios' ? 2 : 14,
  },
  tooltip: {
    backgroundColor: Colors.BlueNewColor,
    paddingHorizontal: 6,
    paddingVertical: 12,
    borderRadius: 13,
    marginLeft: 10,
  },
  tooltipContent: {
    color: Colors.WHITE,
    fontSize: 12,
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    lineHeight: 16,
    textAlign: 'left',
  },
  textBold: {
    fontWeight: 'bold',
    fontSize: 12,
    color: Colors.WHITE,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    lineHeight: 16,
  },
  widthNotRankedText: {
    width: 80,
  },
});
