import { lightColors as Colors } from 'styles';
import { getStylesHook } from 'hooks/useStyles';

export default getStylesHook({
  container: {
    flex: 1,
    backgroundColor: Colors.WHITE,
  },
  container_2: {
    backgroundColor: Colors.WHITE,
    paddingBottom: 20,
    paddingHorizontal: 20,
  },
  tab: {
    flexDirection: 'row',
    height: 44,
    backgroundColor: Colors.LIGHTBGTab,
    borderRadius: 10,
    paddingHorizontal: 3,
    paddingVertical: 3,
    marginBottom: 11,
    marginTop: 8,
  },
  buttonTab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  selectedTab: {
    backgroundColor: Colors.WHITE,
  },
  selectedText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: Colors.BlueNewColor,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    lineHeight: 18,
  },
  unselectedText: {
    fontSize: 14,
    color: Colors.LIGHTTextTitle,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 18,
  },
  title: {
    fontSize: 14,
    color: Colors.LIGHTTextTitle,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: 'bold',
    lineHeight: 18,
  },
  containerSubAccount: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  containerBlock: {
    marginTop: 16,
  },
  containerTextField: {
    width: 160,
    height: 44,
    paddingHorizontal: 10,
    paddingVertical: 13,
  },
  scrollView: {
    marginTop: 10,
    marginHorizontal: -20,
  },
  containerIconBank: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: Colors.BORDER,
    borderWidth: 3,
    borderRadius: 48,
  },
  selectedIconBank: {
    borderColor: Colors.BlueNewColor,
  },
  imageBank: {
    width: 40,
    height: 40,
  },
  nameBank: {
    fontSize: 14,
    color: Colors.BlueNewColor,
    marginTop: 4,
    textAlign: 'center',
  },
  selectedNameBank: {
    fontWeight: 'bold',
  },
  containerItemBank: {
    alignItems: 'center',
    width: 100,
  },
  lastItemBank: {
    marginRight: 20,
  },
  containerData: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: Colors.LIGHTTitleTable,
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
  },
  textNumberAccount: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.BLACK,
  },
  subBank: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.BLACK,
    marginRight: 4,
    flex: 1,
  },
  dot: {
    marginTop: 8,
    width: 4,
    height: 4,
    borderRadius: 4,
    backgroundColor: Colors.BLACK,
    marginHorizontal: 8,
  },
  textNotice: {
    marginTop: 8,
    flexDirection: 'row',
  },
  notice: {
    padding: 10,
    backgroundColor: Colors.Yellow3,
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
  },
  noticeText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.BLACK,
  },
  textSupport: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.BlueNewColor,
  },
});
