import { Platform } from 'react-native';
import { lightColors as Colors } from 'styles';
import { getStylesHook } from 'hooks/useStyles';

export default getStylesHook({
  container: {
    flex: 1,
    backgroundColor: Colors.WHITE,
  },
  modalContainer: {
    flex: 1,
    paddingHorizontal: 16,
    backgroundColor: Colors.BACKGROUND_MODAL2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalContentContainer: {
    backgroundColor: Colors.WHITE,
    borderRadius: 21,
    width: 343,
    paddingHorizontal: 16,
    marginBottom: Platform.OS === 'ios' ? 50 : 0,
    overflow: 'hidden',
  },
  modalContainerSetting: {
    backgroundColor: Colors.WHITE,
    borderRadius: 21,
    width: 343,
    overflow: 'hidden',
  },
  modalTitleContainer: {
    height: 52,
    borderBottomColor: Colors.BORDER,
    borderBottomWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  otpKisContainer: {
    marginTop: 17,
    marginBottom: 16,
  },
  modalTitleText2: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    lineHeight: 24,
    textAlign: 'center',
    color: Colors.BlueNewColor,
  },
  executeFormButton2: {
    backgroundColor: Colors.LIGHTBackground,
    width: '100%',
    height: 44,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    marginTop: 17,
  },
  executeFormButton3: {
    backgroundColor: Colors.BlueNewColor,
    width: '100%',
    height: 44,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    marginTop: 17,
  },
  cancelExecuteFormButton2: {
    backgroundColor: Colors.LIGHTBackground,
    height: 44,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelExecuteFormButtonText2: {
    fontSize: 16,
    color: Colors.LIGHTTextContent,
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
  },
  executeFormButtonText2: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.WHITE,
  },
  executeFormButtonTextDisable: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.LIGHTTextDisable,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
  },

  // modalOpenSetting
  headerModalSetting: {
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomColor: Colors.BORDER,
    borderBottomWidth: 1,
  },
  headerModalSettingTitle: {
    fontSize: 18,
    color: Colors.BlueNewColor,
    fontWeight: '700',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    textAlign: 'center',
  },
  sectionModalSetting: {
    paddingTop: 16,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textSection: {
    fontSize: 14,
    color: Colors.LIGHTTextContent,
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    textAlign: 'center',
  },
  goToSettingButton: {
    marginTop: 17,
    backgroundColor: Colors.BlueNewColor,
    marginHorizontal: 16,
    height: 44,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  cancelButton: {
    backgroundColor: Colors.LIGHTBackground,
    height: 44,
    borderRadius: 10,
    marginHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  titleGroup: {
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomColor: Colors.BORDER,
    borderBottomWidth: 1,
  },
  titleText: {},
});
