import { lightColors as Colors } from 'styles';
import { getStylesHook } from 'hooks/useStyles';

export default getStylesHook({
  container: {
    flex: 1,
    backgroundColor: Colors.WHITE,
  },
  iDCardContainer: {
    alignSelf: 'center',
    marginVertical: 24,
  },
  modalBackground: {
    backgroundColor: Colors.BACKGROUND_MODAL,
    paddingHorizontal: 16,
  },
  modalContentContainer: {
    // alignItems: 'stretch',
    backgroundColor: Colors.WHITE,
    borderRadius: 21,
    width: '100%',
    paddingTop: 10,
    paddingBottom: 20,
  },
  errorTextModal: {
    marginTop: 24,
    marginBottom: 34,
    fontSize: 16,
    fontFamily: 'Roboto',
    fontWeight: '400',
    fontStyle: 'normal',
    lineHeight: 22,
    color: Colors.LIGHTTextContent,
  },
  executeButton2: {
    backgroundColor: Colors.LIGHTButtonRed,
    borderRadius: 10,
  },
  image: {
    height: 193,
    resizeMode: 'cover',
    justifyContent: 'center',
    zIndex: 1,
  },
  image2: {
    height: 193,
  },
  icon: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  uploadSignatureText: {
    fontSize: 14,
    fontFamily: 'Roboto',
    fontWeight: '400',
    fontStyle: 'normal',
    lineHeight: 18,
    color: Colors.LIGHTTextContent,
    marginBottom: 5,
  },
  uploadSignatureAndFullNameText: {
    fontSize: 14,
    fontFamily: 'Roboto',
    fontWeight: '400',
    fontStyle: 'normal',
    lineHeight: 18,
    color: Colors.LIGHTRed,
  },
  uploadContainer: {
    width: '100%',
    height: 193,
    backgroundColor: Colors.LIGHTBGTab,
    opacity: 1,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  zIndexImage: {
    zIndex: -1,
  },
  titleText2: {
    fontSize: 14,
    fontFamily: 'Roboto',
    fontWeight: '400',
    fontStyle: 'normal',
    lineHeight: 18,
    color: Colors.LIGHTTextContent,
    marginBottom: 16,
  },
  titleText: {
    fontSize: 24,
    fontFamily: 'Roboto',
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: 30,
    color: Colors.LIGHTTextBigTitle,
    marginBottom: 12,
    marginTop: 18,
    marginLeft: 10,
  },
  fieldContainer: {
    height: 40,
    marginHorizontal: 16,
  },
  fieldKeyText: {
    fontSize: 14,
    fontFamily: 'Roboto',
    fontWeight: 'bold',
    fontStyle: 'normal',
    lineHeight: 18,
    color: Colors.LIGHTTextTitle,
  },
  fieldValueText: {
    fontSize: 13,
    fontFamily: 'Roboto',
    fontWeight: '400',
    fontStyle: 'normal',
    lineHeight: 16,
    color: Colors.LIGHTTextContent,
    width: 187,
  },
  marginBottom26: {
    marginBottom: 26,
  },
  executeButtonContainer: {
    height: 44,
  },
  executeButton: {
    backgroundColor: Colors.BlueNewColor,
    borderRadius: 10,
  },
  executeButtonText: {
    color: Colors.WHITE,
    fontSize: 16,
    fontFamily: 'Roboto',
    fontWeight: '700',
    fontStyle: 'normal',
    lineHeight: 22,
  },
  genderText: {
    fontSize: 13,
    fontFamily: 'Roboto',
    fontWeight: '400',
    fontStyle: 'normal',
    lineHeight: 16,
    color: Colors.Gray2,
    marginLeft: 16,
    width: 55,
  },
  marginHorizontal16: {
    marginHorizontal: 16,
  },
  wholeContainerStyle: {
    height: 30,
  },
  textInputStyle: {
    width: 100,
    height: '100%',
    fontSize: 14,
    paddingTop: 0,
    paddingBottom: 0,
    // color: Colors.BLACK,
  },
  textInputContainerStyle2: {
    backgroundColor: Colors.LIGHTTitleTable,
    height: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.LIGHTBackground,
  },
  textInputContainerStyleError2: {
    backgroundColor: Colors.red01,
    height: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.Ask1,
  },
  labelTextStyle: {
    color: Colors.LIGHTTextTitle,
    marginBottom: 3,
    fontSize: 14,
    lineHeight: 18,
    fontFamily: 'Roboto',
    fontWeight: '400',
    fontStyle: 'normal',
  },
  checkBoxText: {
    color: Colors.Gray2,
    fontSize: 14,
    lineHeight: 18,
    fontFamily: 'Roboto',
    fontWeight: 'bold',
    fontStyle: 'normal',
  },
  checkBoxContainer: {
    paddingHorizontal: 10,
    height: 40,
    backgroundColor: Colors.LIGHTTitleTable,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.LIGHTBackground,
  },
  checkBoxContainer2: {
    marginTop: 16,
    marginBottom: 24,
    // paddingRight: (14),
  },
  termAndConditionText: {
    marginLeft: 16,
    fontSize: 14,
    lineHeight: 18,
    fontFamily: 'Roboto',
    fontWeight: '400',
    fontStyle: 'normal',
    color: Colors.LIGHTTextContent,
  },
});
