import { lightColors as Colors } from 'styles';
import { getStylesHook } from 'hooks/useStyles';

export default getStylesHook({
  container: {
    flex: 1,
    backgroundColor: Colors.WHITE,
  },
  iDCardContainer: {
    alignSelf: 'center',
    marginVertical: 24,
  },
  headerModalize3: {
    height: 116,
  },
  kisBankItemContainer: {
    height: 58,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: Colors.BORDER,
  },
  kisBankBranchItemContainer: {
    height: 44,
    paddingLeft: 16,
    paddingRight: 139,
    borderBottomWidth: 1,
    borderBottomColor: Colors.BORDER,
  },
  kisBankBranchItemText: {
    fontSize: 14,
    fontFamily: 'Roboto',
    fontWeight: '400',
    fontStyle: 'normal',
    lineHeight: 18,
    color: Colors.LIGHTTextContent,
  },
  kisBankItemText1: {
    fontSize: 14,
    fontFamily: 'Roboto',
    fontWeight: 'bold',
    fontStyle: 'normal',
    lineHeight: 18,
    color: Colors.BlueNewColor,
    marginBottom: 2,
  },
  kisBankItemText2: {
    fontSize: 14,
    fontFamily: 'Roboto',
    fontWeight: '400',
    fontStyle: 'normal',
    lineHeight: 18,
    color: Colors.LIGHTTextDisable,
  },
  bankPickerContainer: {
    height: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.LIGHTBackground,
    backgroundColor: Colors.LIGHTTitleTable,
    paddingHorizontal: 10,
  },
  paddingBottom8: {
    paddingBottom: 8,
  },
  paddingLeft10: {
    paddingLeft: 10,
  },
  textInputContainerStyle: {
    borderRadius: 10,
    backgroundColor: Colors.LIGHTTitleTable,
    borderWidth: 1,
    borderColor: Colors.LIGHTBackground,
  },
  marginHorizontal10: {
    marginHorizontal: 10,
  },
  marginRight16: {
    marginRight: 16,
  },
  bankNameShortDisplay: {
    fontSize: 14,
    fontFamily: 'Roboto',
    fontWeight: '400',
    fontStyle: 'normal',
    lineHeight: 18,
    color: Colors.Gray2,
    flex: 1,
    marginRight: 10,
  },
  modalBackground: {
    backgroundColor: Colors.BACKGROUND_MODAL,
    paddingHorizontal: 16,
  },
  modalContentContainer: {
    // alignItems: 'stretch',
    backgroundColor: Colors.WHITE,
    borderRadius: 21,
    width: '100%',
    paddingTop: 10,
    paddingBottom: 20,
  },
  errorTextModal: {
    marginTop: 24,
    marginBottom: 34,
    fontSize: 16,
    fontFamily: 'Roboto',
    fontWeight: '400',
    fontStyle: 'normal',
    lineHeight: 22,
    color: Colors.LIGHTTextContent,
    marginHorizontal: 20,
  },
  executeButton2: {
    backgroundColor: Colors.LIGHTButtonRed,
    borderRadius: 10,
  },
  headerModalize1: {
    height: 56,
    borderBottomColor: Colors.BORDER,
    borderBottomWidth: 1,
  },
  headerModalize2: {
    height: 60,
  },
  headerModalize1Text: {
    fontSize: 16,
    fontFamily: 'Roboto',
    fontWeight: 'bold',
    fontStyle: 'normal',
    lineHeight: 22,
    color: Colors.BlueNewColor,
    marginLeft: 16,
  },
  titleText: {
    fontSize: 24,
    fontFamily: 'Roboto',
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: 30,
    color: Colors.LIGHTTextBigTitle,
    marginBottom: 10,
    marginTop: 18,
  },
  fieldContainer: {
    height: 40,
    marginHorizontal: 16,
  },
  fieldKeyText: {
    fontSize: 14,
    fontFamily: 'Roboto',
    fontWeight: 'bold',
    fontStyle: 'normal',
    lineHeight: 18,
    color: Colors.LIGHTTextTitle,
    paddingTop: 18,
  },
  fieldValueText: {
    fontSize: 13,
    fontFamily: 'Roboto',
    fontWeight: '400',
    fontStyle: 'normal',
    lineHeight: 16,
    color: Colors.LIGHTTextContent,
    width: 187,
  },
  marginBottom26: {
    marginBottom: 26,
  },
  executeButtonContainer: {
    height: 44,
  },
  executeButtonContainer2: {
    height: 44,
    paddingHorizontal: 20,
  },
  executeButton: {
    backgroundColor: Colors.BlueNewColor,
    borderRadius: 10,
  },
  executeButtonText: {
    color: Colors.WHITE,
    fontSize: 16,
    fontFamily: 'Roboto',
    fontWeight: '700',
    fontStyle: 'normal',
    lineHeight: 22,
  },
  genderText: {
    fontSize: 13,
    fontFamily: 'Roboto',
    fontWeight: '400',
    fontStyle: 'normal',
    lineHeight: 16,
    color: Colors.Gray2,
    marginLeft: 16,
    width: 55,
  },
  marginHorizontal16: {
    marginHorizontal: 16,
  },
  wholeContainerStyle: {
    // height: (30),
    paddingTop: 8,
  },
  wholeContainerStyle2: {
    height: 40,
  },
  textInputStyle: {
    width: 100,
    height: '100%',
    fontSize: 14,
    paddingTop: 0,
    paddingBottom: 0,
    // color: Colors.BLACK,
  },
  textInputStyle2: {
    height: '100%',
    fontSize: 14,
    paddingBottom: 0,
    // color: Colors.BLACK,
    marginHorizontal: 10,
  },
  textInputContainerStyle2: {
    backgroundColor: Colors.LIGHTTitleTable,
    height: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.LIGHTBackground,
  },
  textInputContainerStyleError2: {
    backgroundColor: Colors.red01,
    height: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.Ask1,
  },
  labelTextStyle: {
    color: Colors.LIGHTTextTitle,
    marginBottom: 3,
    fontSize: 14,
    lineHeight: 18,
    fontFamily: 'Roboto',
    fontWeight: '400',
    fontStyle: 'normal',
  },
  checkBoxText: {
    color: Colors.Gray2,
    fontSize: 14,
    lineHeight: 18,
    fontFamily: 'Roboto',
    fontWeight: 'bold',
    fontStyle: 'normal',
  },
  checkBoxContainer: {
    paddingHorizontal: 10,
    height: 40,
    backgroundColor: Colors.LIGHTTitleTable,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.LIGHTBackground,
  },
  checkBoxContainer2: {
    marginTop: 8,
    marginBottom: 30,
    // paddingRight: (14),
  },
  termAndConditionText: {
    marginLeft: 16,
    fontSize: 14,
    lineHeight: 18,
    fontFamily: 'Roboto',
    fontWeight: '400',
    fontStyle: 'normal',
    color: Colors.LIGHTTextContent,
  },
  termAndConditionText2: {
    marginLeft: 16,
    fontSize: 14,
    lineHeight: 18,
    fontFamily: 'Roboto',
    fontWeight: '400',
    fontStyle: 'normal',
    color: Colors.BlueNewColor,
  },
  marginTop10: {
    marginTop: 10,
  },
});
