const vn = require('moment/locale/vi');

export const configLocaleEN = {
  // relativeTime: {
  //   future: 'in %s',
  //   past: '%s',
  //   s: 'a few seconds',
  //   ss: '%s seconds',
  //   m: 'about a minute',
  //   mm: '%d minutes',
  //   h: 'about an hour',
  //   hh: '%d hours',
  //   d: 'about a day',
  //   dd: '%d days',
  //   M: 'about a month',
  //   MM: '%d months',
  //   y: 'about a year',
  //   yy: '%d years',
  // },
};

export const configLocaleVN = {
  ...vn,
  // months: [
  //   'Tháng 1',
  //   'Tháng 2',
  //   'Tháng 3',
  //   'Tháng 4',
  //   'Tháng 5',
  //   'Tháng 6',
  //   'Tháng 7',
  //   'Tháng 8',
  //   'Tháng 9',
  //   'Tháng 10',
  //   'Tháng 11',
  //   'Tháng 12',
  // ],
  // monthsShort: [
  //   'Thg 1',
  //   'Thg 2',
  //   'Thg 3',
  //   'Thg 4',
  //   'Thg 5',
  //   'Thg 6',
  //   'Thg 7',
  //   'Thg 8',
  //   'Thg 9',
  //   'Thg 10',
  //   'Thg 11',
  //   'Thg 12',
  // ],
  // relativeTime: {
  //   future: 'trong %s',
  //   past: '%s',
  //   s: 'khoảng vài giây',
  //   ss: '%s giây',
  //   m: 'khoảng 1 phút',
  //   mm: '%d phút',
  //   h: 'khoảng 1 giờ',
  //   hh: '%d giờ',
  //   d: 'khoảng 1 ngày',
  //   dd: '%d ngày',
  //   M: 'khoảng 1 tháng',
  //   MM: '%d tháng',
  //   y: 'khoảng 1 năm',
  //   yy: '%d năm',
  // },
};
