export enum ErrorMessage {
  USERNAME_INVALID = 'USERNAME_INVALID',
  FULL_NAME_INVALID = 'FULLNAME_INVALID',
  ORDER_PRICE_RANGE_INVALID = 'ORDER_PRICE_RANGE_INVALID',
  WRONG_PRICE_STEP = 'WRONG_PRICESTEP',
  STOP_PRICE_RANGE_INVALID = 'STOP_PRICE_RANGE_INVALID',
  BUY_STOP_PRICE_INVALID = 'BUY_STOP_PRICE_INVALID',
  SELL_STOP_PRICE_INVALID = 'SELL_STOP_PRICE_INVALID',
  ORDER_QUANTITY_BATCH_INVALID = 'ORDER_QUANTITY_BATCH_INVALID',
  ORDER_QUANTITY_LOTS_INVALID = 'ORDER_QUANTITY_LOTS_INVALID',
  OVER_AVAILABLE = 'OVER_AVAILABLE',
  EMAIL_EXISTS = 'EMAIL_EXISTS',
  INVALID_EMAIL = 'Please enter a valid email',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_CONFIRM_PASSWORD = 'Confirm password and password must be same',
  INVALID_OWNERSHIP_STOCK = 'INVALID_OWNERSHIP_STOCK',
  LO_CANCEL_FAILED = 'LO_CANCEL_FAILED',
}

export default ErrorMessage;
