/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'Paave-Icons\'">' + entity + '</span>' + html;
	}
	var icons = {
		'icon-account': '&#xe901;',
		'icon-add': '&#xe902;',
		'icon-apple-id': '&#xe903;',
		'icon-arrow-down': '&#xe913;',
		'icon-arrow-down-2': '&#xe907;',
		'icon-arrow-down-3': '&#xe906;',
		'icon-arrow-down-double': '&#xe908;',
		'icon-arrow-left': '&#xe909;',
		'icon-arrow-left-2': '&#xe90a;',
		'icon-arrow-left-3': '&#xe90b;',
		'icon-arrow-left-double': '&#xe90c;',
		'icon-arrow-right': '&#xe90d;',
		'icon-arrow-right-2': '&#xe90e;',
		'icon-arrow-right-3': '&#xe90f;',
		'icon-arrow-right-double': '&#xe910;',
		'icon-arrow-up': '&#xe912;',
		'icon-arrow-up-2': '&#xe914;',
		'icon-arrow-up-3': '&#xe915;',
		'icon-arrow-up-double': '&#xe916;',
		'icon-asset-info': '&#x1f43f;',
		'icon-at-sign': '&#xe9a2;',
		'icon-author-outline': '&#xe918;',
		'icon-back-space': '&#xe919;',
		'icon-block': '&#xe94a;',
		'icon-book': '&#xe91a;',
		'icon-bookmark': '&#xe94b;',
		'icon-bookmark-outline': '&#xe94f;',
		'icon-calendar': '&#xe91b;',
		'icon-calendar-2': '&#xe91c;',
		'icon-camera': '&#xe950;',
		'icon-camera-2': '&#xe91d;',
		'icon-camera-plus': '&#xe998;',
		'icon-cart': '&#xe91e;',
		'icon-category': '&#xe91f;',
		'icon-chart': '&#xe920;',
		'icon-chart-circle': '&#xe921;',
		'icon-chart-circle-2': '&#xe922;',
		'icon-chart-person': '&#xe925;',
		'icon-chat': '&#xe926;',
		'icon-chat-2': '&#xe927;',
		'icon-check': '&#xe928;',
		'icon-check-circle': '&#xe929;',
		'icon-close': '&#xe92a;',
		'icon-comment': '&#xe92b;',
		'icon-computer': '&#xe92c;',
		'icon-daily': '&#xe92d;',
		'icon-discover': '&#xe92e;',
		'icon-dislike': '&#xe92f;',
		'icon-dislike-ouline': '&#xe930;',
		'icon-document-add': '&#xe931;',
		'icon-dollard': '&#xe932;',
		'icon-drag': '&#xe952;',
		'icon-earth-2': '&#xe953;',
		'icon-earth-outline': '&#xe951;',
		'icon-edit': '&#xe933;',
		'icon-emoji': '&#xe955;',
		'icon-emoji-outline': '&#xe96f;',
		'icon-error': '&#xe934;',
		'icon-eye': '&#xe970;',
		'icon-face-id': '&#xe936;',
		'icon-facebook': '&#xe937;',
		'icon-favorite': '&#xe938;',
		'icon-favorite-outline': '&#xe939;',
		'icon-filter': '&#xe93a;',
		'icon-filter-setting': '&#xe93b;',
		'icon-flag': '&#xe954;',
		'icon-follow': '&#xe93c;',
		'icon-g-translate': '&#xe974;',
		'icon-google': '&#xe93d;',
		'icon-hash': '&#xe971;',
		'icon-hide-keyboard': '&#xe93e;',
		'icon-hide-pass': '&#xe93f;',
		'icon-home': '&#xe940;',
		'icon-id-assport': '&#xe941;',
		'icon-image-outline': '&#xe975;',
		'icon-images': '&#xe942;',
		'icon-increase': '&#xe943;',
		'icon-increase-reduced': '&#xe944;',
		'icon-info': '&#xe945;',
		'icon-internal-transfer': '&#xe99b;',
		'icon-invite-friend': '&#xe946;',
		'icon-library-books': '&#xe98e;',
		'icon-like': '&#xe947;',
		'icon-like-outline': '&#xe948;',
		'icon-line': '&#xe900;',
		'icon-live-outline': '&#xe94c;',
		'icon-location': '&#xe94d;',
		'icon-lock': '&#xe94e;',
		'icon-logout': '&#xe956;',
		'icon-mail': '&#xe957;',
		'icon-market-chart': '&#xe958;',
		'icon-market-chart-candle': '&#xe959;',
		'icon-martket-chart-2': '&#xe95a;',
		'icon-menu': '&#xe95b;',
		'icon-menu-2': '&#xe98f;',
		'icon-message': '&#xe99d;',
		'icon-minus': '&#xe95c;',
		'icon-minus-2': '&#xe95d;',
		'icon-mobile': '&#xe95e;',
		'icon-mobile-rotate': '&#xe904;',
		'icon-moon': '&#xe95f;',
		'icon-new-post': '&#xe960;',
		'icon-notebook': '&#xe961;',
		'icon-notice': '&#xe962;',
		'icon-notification': '&#xe963;',
		'icon-notification-outline': '&#xe964;',
		'icon-payment': '&#xe965;',
		'icon-person-add': '&#xe990;',
		'icon-person-add-disabled': '&#xe994;',
		'icon-phone': '&#xe966;',
		'icon-photo-library': '&#xe995;',
		'icon-plane': '&#xe96a;',
		'icon-plus': '&#xe96b;',
		'icon-poll': '&#xe996;',
		'icon-poll-outline': '&#xe997;',
		'icon-portfolio-2': '&#xe905;',
		'icon-post': '&#xe96c;',
		'icon-question-2': '&#xe96d;',
		'icon-question-outline': '&#xe96e;',
		'icon-quote': '&#xe972;',
		'icon-reduced': '&#xe973;',
		'icon-repeat': '&#xe949;',
		'icon-reply': '&#xe999;',
		'icon-safety': '&#xe976;',
		'icon-search': '&#xe977;',
		'icon-send': '&#xe978;',
		'icon-series-candlestick': '&#xe911;',
		'icon-series-indicators': '&#xe917;',
		'icon-series-line': '&#xe935;',
		'icon-series-ohlc': '&#xe967;',
		'icon-setting': '&#xe979;',
		'icon-share': '&#xe97a;',
		'icon-share-1': '&#xe98d;',
		'icon-share-2': '&#xe97b;',
		'icon-show-pass': '&#xe97c;',
		'icon-social': '&#xe97d;',
		'icon-sort-down': '&#xe97e;',
		'icon-sort-up': '&#xe97f;',
		'icon-star': '&#xe980;',
		'icon-star-outline': '&#xe981;',
		'icon-stock-transfer': '&#xe968;',
		'icon-sun': '&#xe982;',
		'icon-support': '&#xe983;',
		'icon-tag': '&#xe984;',
		'icon-tag-2': '&#xe99e;',
		'icon-touch-id': '&#xe985;',
		'icon-trade-history': '&#xe986;',
		'icon-trading': '&#xe987;',
		'icon-trash': '&#xe988;',
		'icon-trophy': '&#xe989;',
		'icon-uniE900': '&#xe969;',
		'icon-up-down-order': '&#xe98a;',
		'icon-user': '&#xe98b;',
		'icon-user-2': '&#xe98c;',
		'icon-user-guide': '&#xe991;',
		'icon-utilities': '&#xe99c;',
		'icon-video': '&#xe992;',
		'icon-view-list': '&#xe993;',
		'icon-volume-off': '&#xe99f;',
		'icon-zoom-in': '&#xe99a;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
