import { lightColors as Colors } from 'styles';
import { getStylesHook } from 'hooks/useStyles';

export default getStylesHook({
  container: {
    backgroundColor: Colors.WHITE,
  },
  screenOption: {
    marginTop: 10,
    marginBottom: 8,
    width: 343,
    marginHorizontal: 16,
    height: 44,
    backgroundColor: Colors.LIGHTBGTab,
    borderRadius: 10,
    paddingHorizontal: 3,
    paddingVertical: 3,
  },
  TabOptionContainer: {
    height: 38,
    width: 166,
    borderRadius: 10,
  },
  optionContainer: {
    borderRadius: 10,
  },
  optionContainerSelected: {
    backgroundColor: Colors.WHITE,
  },
  selectedText: {
    fontSize: 14,
    fontWeight: '700',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.BlueNewColor,
  },
  unselectedText: {
    fontSize: 14,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.LIGHTTextTitle,
  },
  titleContainer: {
    backgroundColor: Colors.WHITE,
  },
  Title: {
    fontWeight: '700',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 14,
    color: Colors.LIGHTText,
    width: 160,
  },
  title: {
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 14,
    color: Colors.LIGHTTextContent,
    alignItems: 'flex-end',
  },
  titleAre: {
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 16,
    color: Colors.LIGHTTextContent,
  },
  TitleStock: {
    fontWeight: '700',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 14,
    color: Colors.LIGHTText,
    marginVertical: 22,
    width: 160,
  },
  TextBeneficiaryListContainer: {
    height: 44,
    width: 178,
    marginLeft: 5,
  },
  labelIconStyle: {
    width: 24,
    height: 24,
    color: Colors.LIGHTTextDisable,
  },
  textCenter: {
    color: Colors.LIGHTTextContent,
    fontSize: 14,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
  },
  text: {
    color: Colors.LIGHTTextContent,
    fontSize: 14,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    marginRight: 6,
  },
  textSymbol: {
    color: Colors.LIGHTTextContent,
    fontSize: 14,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
  },
  tableStyle: {
    marginTop: 8,
    // height: (510),
  },
  tableStockStyle: {
    height: 120,
  },
  textQtt: {
    color: Colors.LIGHTTextContent,
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    alignItems: 'flex-end',
    paddingRight: 6,
  },
  textAreaBlock: {
    width: 343,
    marginTop: 24,
  },
  optionTitle: {
    fontSize: 14,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '700',
    color: Colors.LIGHTTextBigTitle,
  },
  wholeContainerStyle: {
    width: 343,
    height: 44,
    marginTop: 9,
    marginBottom: 8,
    backgroundColor: Colors.LIGHTTitleTable,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.LIGHTBackground,
  },
  ContentContainerStyle: {
    height: 44,
    width: 280,
  },
  textInputContainerStyle: {
    width: 210,
    height: 44,
    marginTop: 9,
    marginBottom: 8,
    marginLeft: 81,
    backgroundColor: Colors.LIGHTTitleTable,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.LIGHTBackground,
  },
  textInputContainerContainerStyle: {
    borderWidth: 1,
    borderRadius: 10,
    borderColor: Colors.BORDER,
    backgroundColor: Colors.LIGHTTitleTable,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  textInputStyle: {
    height: '100%',
    fontSize: 14,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.BLACK,
    marginLeft: 10,
    width: 230,
  },
  textInputQttStyle: {
    fontSize: 14,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.BLACK,
    marginRight: 10,
  },
  executeFormButton: {
    backgroundColor: Colors.BlueNewColor,
    height: 44,
    width: 343,
    borderRadius: 10,
  },
  executeFormButtonText: {
    fontSize: 16,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '700',
    color: Colors.WHITE,
  },
  opacityBackground: {
    backgroundColor: Colors.BACKGROUND_MODAL2,
  },
  editMarginBottom: {
    marginBottom: 5,
  },
  executeFormContainer: {
    marginTop: 96,
  },
  nameText: {
    fontSize: 14,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '700',
    color: Colors.BlueNewColor,
    lineHeight: 18,
    width: 50,
  },
  textInputStyle2: {
    fontSize: 14,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
  },
  iconSearch: {
    marginLeft: 0,
  },
  marginBottom16: {
    marginBottom: 16,
  },
  marginBottom8: {
    marginBottom: 8,
  },
  marginLeft16: {
    marginLeft: 16,
  },
  marginRight16: {
    marginRight: 16,
  },
  titleTransfer: {
    marginTop: 32,
  },
  TransferQttContainerStyle: {
    height: 39,
    width: 136,
  },
  textTransferQttInputContainerStyle: {
    borderWidth: 1,
    borderRadius: 10,
    borderColor: Colors.BORDER,
    backgroundColor: Colors.LIGHTTitleTable,
    alignItems: 'flex-end',
  },
  CustomPicker: {
    marginLeft: 5,
  },
  wholeContainerContentStyle: {
    width: 136,
    height: 36,
  },
  textInputContainerContentStyle: {
    borderWidth: 1,
    borderRadius: 10,
    borderColor: Colors.BORDER,
    backgroundColor: Colors.LIGHTTitleTable,
    paddingHorizontal: 8,
  },
  textInputTransferQttStyle: {
    fontSize: 14,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    height: 36,
    width: 125,
  },
  errorTransferQttStyle: {
    borderColor: Colors.LIGHTRed2,
    borderWidth: 1,
    borderRadius: 10,
    height: 36,
  },
  ContentError: {
    color: Colors.LIGHTRed2,
    marginTop: 3,
  },
  pickerModalStyle: {
    paddingHorizontal: 16,
  },
  SeparatorContainer: {
    width: '100%',
    backgroundColor: Colors.LIGHTTitleTable,
  },
  modalContentContainer: {
    backgroundColor: Colors.WHITE,
    borderRadius: 21,
    width: 343,
    paddingBottom: 16,
    marginTop: 40,
  },
  modalTitle: {
    height: 52,
    borderBottomWidth: 1,
    borderBottomColor: Colors.BORDER,
  },
  cancelContainer: {
    right: 0,
  },
  iconClose: {
    marginRight: 16,
  },
  listBankContainer: {
    height: 500,
  },
  TextSymbol: {
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 14,
    color: Colors.LIGHTTextContent,
    marginLeft: 10,
    width: 178,
  },
  rowData: {
    paddingHorizontal: 16,
    paddingVertical: 13,
    maxHeight: 44,
    borderBottomColor: Colors.BORDER,
    borderBottomWidth: 1,
    justifyContent: 'space-between',
  },
  rowDataSymbol: {
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 14,
    color: Colors.LIGHTTextDisable,
    alignItems: 'flex-end',
  },
  textBlockStyle: {
    height: 44,
    marginHorizontal: 16,
  },
  executeFormDisableButton: {
    opacity: 0.5,
  },

  btn: {
    borderRadius: 6,
    borderWidth: 1,
    padding: 3.5,
    borderColor: Colors.LIGHTTextDisable,
  },
  btnIsVisible: {
    backgroundColor: Colors.BlueNewColor,
    padding: 3.5,
    borderRadius: 6,
  },

  // fix border right
  borderRightCell: {
    borderRightColor: Colors.BORDER,
    borderRightWidth: 1,
  },
  filterTextValueType: {
    fontSize: 16,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
  },
  topInfo: {
    height: 14,
  },
  filterText: {
    fontWeight: '700',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 16,
    color: Colors.BlueNewColor,
    marginLeft: 16,
  },
  closeType: {
    marginRight: 16,
  },
  filterTextValueSelected: {
    color: Colors.MainBlue,
  },
  filterTextValueUnselected: {
    color: Colors.LIGHTTextTitle,
  },
  filterItemContainer: {
    paddingHorizontal: 16,
    height: 54,
    borderBottomWidth: 1,
    borderBottomColor: Colors.BORDER,
  },
  modalBackground: {
    backgroundColor: Colors.BACKGROUND_MODAL2,
  },
  modalContentContainer1: {
    backgroundColor: Colors.WHITE,
    borderTopLeftRadius: 21,
    borderTopRightRadius: 21,
    width: '100%',
    paddingBottom: 30,
  },
  BeneficiaryTextInputContainerStyle: {
    width: 178,
    height: 44,
    backgroundColor: Colors.LIGHTTitleTable,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.LIGHTBackground,
    paddingHorizontal: 8,
  },
  TransferText: {
    fontWeight: '700',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 12,
    color: Colors.WHITE,
  },
  TransferButton: {
    width: 113,
    height: 26,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.BlueNewColor,
    borderRadius: 10,
  },
  TransferButtonDisabled: {
    width: 113,
    height: 26,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.BlueNewColor,
    borderRadius: 10,
    opacity: 0.5,
  },
  wrapSheet: {
    height: 450,
    paddingBottom: 8,
  },
  modalTitleText: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.BlueNewColor,
  },
  contentBlock: {
    marginHorizontal: 16,
  },
  optionValue: {
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    color: Colors.LIGHTTextContent,
  },
  marginTop17: {
    marginTop: 22,
  },
  executeFormButtonText2: {
    fontSize: 16,
    fontWeight: 'bold',
    color: Colors.WHITE,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
  },
  cancelExecuteFormButtonText2: {
    fontSize: 16,
    color: Colors.LIGHTTextContent,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '400',
  },
  modalActionGroup: {
    marginTop: 10,
  },
  modalCancelButton: {
    backgroundColor: Colors.LIGHTBackground,
    height: 44,
    borderRadius: 10,
    // marginBottom: (10),
  },
  executeFormButton2: {
    backgroundColor: Colors.BlueNewColor,
    height: 44,
    borderRadius: 10,
  },
  executeFormButton3Disable: {
    backgroundColor: Colors.LIGHTBackground,
    width: '100%',
    height: 44,
    borderRadius: 10,
  },
  textInputTransferAmount: {
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontSize: 14,
    height: '100%',
  },
  textInputContainerContentError: {
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: Colors.LIGHTTitleTable,
    paddingHorizontal: 8,
    borderColor: Colors.LIGHTRed,
  },
  iconStyle: {
    marginRight: 10,
  },
  marginHorizontal16: {
    marginTop: 20,
    paddingHorizontal: 16,
  },
  executeFormButton3: {
    backgroundColor: Colors.BlueNewColor,
    width: '100%',
    height: 44,
    borderRadius: 10,
  },
  cancelExecuteFormButton2: {
    backgroundColor: Colors.LIGHTBackground,
    height: 44,
    borderRadius: 10,
  },
  executeFormButtonTextDisable: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.LIGHTTextDisable,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
  },
  marginBottom10: {
    marginBottom: 10,
  },
  loadingText: {
    fontWeight: '400',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    textAlign: 'center',
    color: Colors.LIGHTTextDisable,
  },
  noDataCon: {
    width: 375,
    height: 162,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noDataText: {
    fontFamily: 'Roboto',
    marginTop: 16,
    fontSize: 16,
    color: Colors.LIGHTTextContent,
    textAlign: 'center',
  },
  scrollView: {
    paddingVertical: 40,
  },
});
